/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniproject;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

 
/*
 * @author Arya
 */
public class Cart1 extends javax.swing.JFrame {

    /**
     * Creates new form Cart1
     */
    public Cart1() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        close_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcusname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtmobno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        menu_name = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtcost = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        clear_btn = new javax.swing.JButton();
        add_crt = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        cart_tab = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        grd_total = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtbill = new javax.swing.JTextArea();
        print_btn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniproject/JFrame Cafe Image & Icon/Cafe Image & Icon/images/place order.png"))); // NOI18N
        jLabel1.setText("Place Order");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 40));

        close_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniproject/JFrame Cafe Image & Icon/Cafe Image & Icon/images/close.png"))); // NOI18N
        close_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_btnActionPerformed(evt);
            }
        });
        getContentPane().add(close_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 20, 40, 40));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel3.setText("Customer Details:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 170, -1));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel4.setText("Name:- ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 90, -1));

        txtcusname.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        getContentPane().add(txtcusname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 190, 30));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel5.setText("Mobile No :-");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 100, -1));

        txtmobno.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        getContentPane().add(txtmobno, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 170, 30));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel6.setText("Email:- ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 90, 30));

        txtemail.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 200, 30));

        jLabel7.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel7.setText("Category");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 90, -1));

        jComboBox1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Starters", "Soups", "Main Course", "Desserts", "" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 150, -1));

        menu_name.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        menu_name.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        menu_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_nameMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(menu_name);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 230, 260));

        jLabel9.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel9.setText("Item");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 70, -1));

        txtname.setEditable(false);
        txtname.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 140, -1));

        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 90, -1));

        jLabel10.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel10.setText("Quantity");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 80, -1));

        jLabel11.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel11.setText("Price");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 40, 80, -1));

        txtcost.setEditable(false);
        txtcost.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        getContentPane().add(txtcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 70, 120, -1));

        jLabel12.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel12.setText("Total");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 110, 90, 30));

        txttotal.setEditable(false);
        txttotal.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        getContentPane().add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 140, 120, -1));

        clear_btn.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        clear_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniproject/JFrame Cafe Image & Icon/Cafe Image & Icon/images/clear.png"))); // NOI18N
        clear_btn.setText("Clear");
        clear_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });
        getContentPane().add(clear_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 100, 30));

        add_crt.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        add_crt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniproject/JFrame Cafe Image & Icon/Cafe Image & Icon/images/add to cart.png"))); // NOI18N
        add_crt.setText("Add to Cart");
        add_crt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add_crt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_crtActionPerformed(evt);
            }
        });
        getContentPane().add(add_crt, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 180, 120, -1));

        cart_tab.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        cart_tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Price", "Quantity", "Total"
            }
        ));
        jScrollPane2.setViewportView(cart_tab);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 370, 280));

        jLabel13.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel13.setText("Grand Total");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 550, 100, 30));

        jButton4.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniproject/JFrame Cafe Image & Icon/Cafe Image & Icon/images/login.png"))); // NOI18N
        jButton4.setText("Generate Bill ");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 550, 140, -1));

        jLabel8.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel8.setText("Search");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 50, 20));

        jTextField4.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 150, 30));

        jButton5.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniproject/JFrame Cafe Image & Icon/Cafe Image & Icon/images/search.png"))); // NOI18N
        jButton5.setText("Search");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 90, -1));

        grd_total.setEditable(false);
        grd_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grd_totalActionPerformed(evt);
            }
        });
        getContentPane().add(grd_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 540, 110, 40));

        txtbill.setColumns(20);
        txtbill.setRows(5);
        jScrollPane3.setViewportView(txtbill);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 200, 350, 360));

        print_btn.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        print_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniproject/JFrame Cafe Image & Icon/Cafe Image & Icon/images/generate bill & print.png"))); // NOI18N
        print_btn.setText("Print");
        print_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        print_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_btnActionPerformed(evt);
            }
        });
        getContentPane().add(print_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 570, 90, -1));

        jLabel15.setFont(new java.awt.Font("Lucida Handwriting", 1, 48)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("QuickGo");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 270, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniproject/cart back.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        txtname.setText("");
        txtcost.setText(""); 
        txttotal.setText("");
        jSpinner1.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_clear_btnActionPerformed

    private void close_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_btnActionPerformed
     setVisible(false);
     new HomePage().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_close_btnActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        try{
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/minp_login","root","Secreteng@4307");
        String sql = "SELECT * FROM categories";
        PreparedStatement pst = con.prepareStatement(sql);
        ResultSet rs = pst.executeQuery(sql);
        DefaultTableModel tblModel = (DefaultTableModel)menu_name.getModel();
        tblModel.setRowCount(0);
        String name;
        
         while(rs.next()){
            name=rs.getString(2);
            
           String[] row= {name};
         tblModel.addRow(row);
        }
        }
        
        catch(Exception e){
        System.out.println("Error :"+ e.getMessage());
        }
          
              // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void menu_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_nameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_nameMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      
        try {  
            
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/minp_login","root","Secreteng@4307");
         String sql = "SELECT * FROM allfood";
        PreparedStatement pst = con.prepareStatement("select name,cost from allfood where name=? ");
         
            String name = jTextField4.getText();
            pst.setString(1,name);
            
       
             
            ResultSet rs = pst.executeQuery();
                       if(rs.next()==false)
{
                                JOptionPane.showMessageDialog(this, "Sorry Record Not Found");
                                txtname.setText("");
                                txtcost.setText("");
                               
        }
                        else
                        {
 
                        txtname.setText(rs.getString("name"));
                        txtcost.setText(rs.getString("cost"));
                        
                        
}
            
        } catch (Exception e) {
            System.out.println(e.getMessage());  
        }
        
        jTextField4.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
       try {  
            
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/minp_login","root","Secreteng@4307");
         String sql = "SELECT * FROM allfood";
        PreparedStatement pst = con.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();
         
            int productPrice = Integer.parseInt(txtcost.getText());
            int productTotal;
             int quantity = Integer.parseInt(jSpinner1.getValue().toString());    
           
           productTotal = quantity * productPrice;
           txttotal.setText(String.valueOf(productTotal));
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
            
        }
    



// TODO add your handling code here:
    }//GEN-LAST:event_jSpinner1StateChanged

    private void add_crtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_crtActionPerformed
   
        DefaultTableModel tblModel = (DefaultTableModel)cart_tab.getModel();
        tblModel.addRow(new Object[]
                
        { 
            txtname.getText(),
            txtcost.getText(),
            jSpinner1.getValue().toString(),
            txttotal.getText()
        });
        
        int sum=0;
        for(int i=0; i< cart_tab.getRowCount();i++)
        {
            sum=sum+Integer.parseInt(cart_tab.getValueAt(i,3).toString());
        }
        
         txtname.setText("");
        txtcost.setText("");
        txttotal.setText("");
        jSpinner1.setValue(1);
        
         int numrow = cart_tab.getRowCount();
        double tot=0;
        
        for (int i=0;i<numrow;i++)
        {
            double val = Double.parseDouble(cart_tab.getValueAt(i, 3).toString());
            tot=tot+val;
        }
        
        grd_total.setText(Double.toString(tot));// TODO add your handling code here:
               // TODO add your handling code here:
    }//GEN-LAST:event_add_crtActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       DefaultTableModel tblModel = (DefaultTableModel)cart_tab.getModel();
       if(tblModel.getRowCount()==0){
           JOptionPane.showMessageDialog(this,"Cart is empty");
       }else{
           
           String name,price,quantity,total;
           try{
               Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/minp_login","root","Secreteng@4307");
        
        for(int i=0;i<tblModel.getRowCount();i++)
        {
            name=tblModel.getValueAt(i, 0).toString();
            price=tblModel.getValueAt(i, 1).toString();
            quantity=tblModel.getValueAt(i, 2).toString();
            total=tblModel.getValueAt(i, 3).toString();
            
            String query ="insert into orders(name,price,quantity,total)values(?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1,name);
            pst.setString(2,price);
            pst.setString(3,quantity);
            pst.setString(4,total);
            pst.execute();
        }
        JOptionPane.showMessageDialog(this, "Successful inserted");
           }catch(Exception e){
                
                }  
       }
        if(txtcusname.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Name is Mandatory!");
        
       else if(txtmobno.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Mobile Number is Mandatory!");
        else if(txtemail.getText().equals(""))
             JOptionPane.showMessageDialog(null, "Email is Mandatory!");   
        else
        {
        
        String cusname=txtcusname.getText();
         String mbno = txtmobno.getText();
         String email = txtemail.getText();
         String choice = txtname.getText();
         String quantity = jSpinner1.getValue().toString();
         String total = grd_total.getText();
         
         DefaultTableModel model =new DefaultTableModel();
         model = (DefaultTableModel)cart_tab.getModel();
         
          SimpleDateFormat sdf =new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
         
         Date date =new Date();

         
         txtbill.setText(txtbill.getText() + " ***********************************************************\n");
         txtbill.setText(txtbill.getText() + "                              QuickGo                       \n");
         txtbill.setText(txtbill.getText() + " ***********************************************************\n");
         txtbill.setText(txtbill.getText() + "\n");
         txtbill.setText(txtbill.getText() + sdf.format(date)+ "\n");
         txtbill.setText(txtbill.getText() + " Name :  " + cusname + "\n");
         txtbill.setText(txtbill.getText() + " Mobile Number :  " + mbno + "\n");
         txtbill.setText(txtbill.getText() + " Email :  " + email + "\n");
         txtbill.setText(txtbill.getText() + " ***********************************************************\n");
         
         txtbill.setText(txtbill.getText() + "Name"+"\t" + "Price"+"\t" + "Quantity "+"\t" + "Total"+"\t" + "\n"); 
         for(int i=0; i<model.getRowCount(); i++)
         {
             String pname = (String)model.getValueAt(i, 0);
             String price = (String)model.getValueAt(i, 1);
             String pquant = (String)model.getValueAt(i, 2);
             String ptotal = (String)model.getValueAt(i, 3);
             
             txtbill.setText(txtbill.getText() + pname +"\t" + price +"\t" + pquant +"\t" + ptotal +"\t" + "\n"); 
         }
         txtbill.setText(txtbill.getText() + "\n");
         txtbill.setText(txtbill.getText() + "\n");
         txtbill.setText(txtbill.getText() + " ***********************************************************\n");
         txtbill.setText(txtbill.getText() + "\t \t Grand Total: " + total +  "\n"); 
         txtbill.setText(txtbill.getText() + "\t \t To Pay: " + total);
      
        }
         
    









// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void grd_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grd_totalActionPerformed
      
    }//GEN-LAST:event_grd_totalActionPerformed

    private void print_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_btnActionPerformed
      
        try {
            txtbill.print();// TODO add your handling code here:
        } catch (PrinterException ex) {
            Logger.getLogger(Cart1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_print_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cart1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cart1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cart1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cart1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cart1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_crt;
    private javax.swing.JTable cart_tab;
    private javax.swing.JButton clear_btn;
    private javax.swing.JButton close_btn;
    private javax.swing.JTextField grd_total;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTable menu_name;
    private javax.swing.JButton print_btn;
    private javax.swing.JTextArea txtbill;
    private javax.swing.JTextField txtcost;
    private javax.swing.JTextField txtcusname;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtmobno;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
