/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniproject;
import javax.swing.JOptionPane;
/**
 *
 * @author Arya
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        orderhis_btn = new javax.swing.JButton();
        feedback_btn = new javax.swing.JButton();
        tems_btn = new javax.swing.JButton();
        contact_btn = new javax.swing.JButton();
        profile_btn = new javax.swing.JButton();
        cart_btn = new javax.swing.JButton();
        soups_btn = new javax.swing.JButton();
        starter_btn = new javax.swing.JButton();
        mncrs_btn = new javax.swing.JButton();
        dess_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        adm_btn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("Home");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 50, 30));

        orderhis_btn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        orderhis_btn.setText("Order History");
        orderhis_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderhis_btnActionPerformed(evt);
            }
        });
        getContentPane().add(orderhis_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 190, 50));

        feedback_btn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        feedback_btn.setText("Feedback/Suggestions");
        feedback_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedback_btnActionPerformed(evt);
            }
        });
        getContentPane().add(feedback_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 190, 50));

        tems_btn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tems_btn.setText("Terms & Conditions");
        tems_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tems_btnActionPerformed(evt);
            }
        });
        getContentPane().add(tems_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 190, 50));

        contact_btn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        contact_btn.setText("Contact Us");
        contact_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contact_btnActionPerformed(evt);
            }
        });
        getContentPane().add(contact_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 190, 50));

        profile_btn.setText("Logout");
        profile_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profile_btnActionPerformed(evt);
            }
        });
        getContentPane().add(profile_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, -1, -1));

        cart_btn.setText("My Cart");
        cart_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cart_btnActionPerformed(evt);
            }
        });
        getContentPane().add(cart_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, -1, -1));

        soups_btn.setBackground(new java.awt.Color(153, 255, 102));
        soups_btn.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        soups_btn.setText("Soups");
        soups_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        soups_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soups_btnActionPerformed(evt);
            }
        });
        getContentPane().add(soups_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 180, 80));

        starter_btn.setBackground(new java.awt.Color(153, 255, 102));
        starter_btn.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        starter_btn.setText("Starters");
        starter_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        starter_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                starter_btnActionPerformed(evt);
            }
        });
        getContentPane().add(starter_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 170, 80));

        mncrs_btn.setBackground(new java.awt.Color(153, 255, 102));
        mncrs_btn.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        mncrs_btn.setText("Main Courses");
        mncrs_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mncrs_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mncrs_btnActionPerformed(evt);
            }
        });
        getContentPane().add(mncrs_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 190, 90));

        dess_btn.setBackground(new java.awt.Color(153, 255, 102));
        dess_btn.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        dess_btn.setText("Desserts");
        dess_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dess_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dess_btnActionPerformed(evt);
            }
        });
        getContentPane().add(dess_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 180, 80));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Categories");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 220, 60));

        adm_btn.setText("Admin");
        adm_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adm_btnActionPerformed(evt);
            }
        });
        getContentPane().add(adm_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 70, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 630, 630));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniproject/FINAL.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 900, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\patil\\Documents\\NetBeansProjects\\MiniProject\\src\\miniproject\\homepagelayout.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tems_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tems_btnActionPerformed
     dispose();
     TandC disp1 = new TandC();
     disp1.show();// TODO add your handling code here:
    }//GEN-LAST:event_tems_btnActionPerformed

    private void feedback_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedback_btnActionPerformed
      dispose();
        Feedback hpage1;
        hpage1 = new Feedback();
      hpage1.show();  // TODO add your handling code here:
    }//GEN-LAST:event_feedback_btnActionPerformed

    private void orderhis_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderhis_btnActionPerformed
       dispose();
        OrderHis hpage1 = new OrderHis();
      hpage1.show();        // TODO add your handling code here:
    }//GEN-LAST:event_orderhis_btnActionPerformed

    private void cart_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cart_btnActionPerformed
    setVisible(false);
    new Cart1().setVisible(true);
   // TODO add your handling code here:
    }//GEN-LAST:event_cart_btnActionPerformed

    private void profile_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profile_btnActionPerformed
        dispose();
        Login hpage2;
        hpage2 = new Login();
      hpage2.show();// TODO add your handling code here:
    }//GEN-LAST:event_profile_btnActionPerformed

    private void adm_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adm_btnActionPerformed

        JOptionPane.showMessageDialog(this, "Warning! Only For Admin");
        dispose();
        AdminLogin disp =new AdminLogin();
        disp.show();
                 // TODO add your handling code here:
    }//GEN-LAST:event_adm_btnActionPerformed

    private void contact_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contact_btnActionPerformed
       dispose();
        Contactus disp = new Contactus();
        disp.show();        // TODO add your handling code here:
    }//GEN-LAST:event_contact_btnActionPerformed

    private void mncrs_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mncrs_btnActionPerformed
    dispose();
    mainCourse disp6 = new mainCourse();
    disp6.show();
    
    }//GEN-LAST:event_mncrs_btnActionPerformed

    private void soups_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soups_btnActionPerformed
     dispose();
     soups disp3 = new soups();
     disp3.show();// TODO add your handling code here:
    }//GEN-LAST:event_soups_btnActionPerformed

    private void dess_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dess_btnActionPerformed
    dispose();
    Desserts disp5 = new Desserts ();
    disp5.show();// TODO add your handling code here:
    }//GEN-LAST:event_dess_btnActionPerformed

    private void starter_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_starter_btnActionPerformed
    dispose();
    starters disp7 = new starters();
    disp7.show();
// TODO add your handling code here:
    }//GEN-LAST:event_starter_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adm_btn;
    private javax.swing.JButton cart_btn;
    private javax.swing.JButton contact_btn;
    private javax.swing.JButton dess_btn;
    private javax.swing.JButton feedback_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mncrs_btn;
    private javax.swing.JButton orderhis_btn;
    private javax.swing.JButton profile_btn;
    private javax.swing.JButton soups_btn;
    private javax.swing.JButton starter_btn;
    private javax.swing.JButton tems_btn;
    // End of variables declaration//GEN-END:variables
}
