/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniproject;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author HARSHAL
 */
public class Profile extends javax.swing.JFrame {

    /**
     * Creates new form Profile
     */
    public Profile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        namefld = new javax.swing.JTextField();
        mobfld = new javax.swing.JTextField();
        add_fld = new javax.swing.JTextField();
        email_fld = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rst_btn = new javax.swing.JButton();
        create_btn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        pass_fld = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("Create new Profile");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 350, 60));

        namefld.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        namefld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namefldActionPerformed(evt);
            }
        });
        jPanel1.add(namefld, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 80, 216, 41));

        mobfld.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        mobfld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobfldActionPerformed(evt);
            }
        });
        jPanel1.add(mobfld, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 154, 216, 41));

        add_fld.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add_fld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_fldActionPerformed(evt);
            }
        });
        jPanel1.add(add_fld, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 228, 216, 41));

        email_fld.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        email_fld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_fldActionPerformed(evt);
            }
        });
        jPanel1.add(email_fld, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 216, 41));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setLabelFor(add_fld);
        jLabel3.setText("Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 170, 41));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setLabelFor(add_fld);
        jLabel4.setText("Address:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 224, 141, 44));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 242, 242));
        jLabel5.setLabelFor(add_fld);
        jLabel5.setText("Mobile No:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 153, -1, 38));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 242, 242));
        jLabel6.setLabelFor(add_fld);
        jLabel6.setText("Email-Id:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 125, 44));

        rst_btn.setBackground(new java.awt.Color(153, 51, 0));
        rst_btn.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        rst_btn.setForeground(new java.awt.Color(242, 242, 242));
        rst_btn.setText("Reset Account");
        rst_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rst_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rst_btnActionPerformed(evt);
            }
        });
        jPanel1.add(rst_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, 153, 34));

        create_btn.setBackground(new java.awt.Color(153, 51, 0));
        create_btn.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        create_btn.setForeground(new java.awt.Color(242, 242, 242));
        create_btn.setText("Create Account");
        create_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        create_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_btnActionPerformed(evt);
            }
        });
        jPanel1.add(create_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(688, 469, 153, 34));

        jLabel7.setForeground(new java.awt.Color(242, 242, 242));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniproject/Profile.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 6, -1, -1));
        jPanel1.add(pass_fld, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 226, 43));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(242, 242, 242));
        jLabel8.setText("Password:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 125, 30));

        jButton1.setBackground(new java.awt.Color(153, 51, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(242, 242, 242));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 470, 87, 34));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniproject/prof back.jpg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 520));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namefldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namefldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namefldActionPerformed

    private void mobfldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobfldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobfldActionPerformed

    private void add_fldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_fldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_fldActionPerformed

    private void email_fldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_fldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_fldActionPerformed

    private void rst_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rst_btnActionPerformed
       namefld.setText("");
        add_fld.setText("");
        mobfld.setText("");
        email_fld.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_rst_btnActionPerformed

    private void create_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_btnActionPerformed
       if(namefld.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Name is Mandatory!");
        
       else if(add_fld.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Address is Mandatory!");
        else if(pass_fld.getText().equals(""))
             JOptionPane.showMessageDialog(null, "Password is Mandatory!");   
        else if(mobfld.getText().equals(""))
             JOptionPane.showMessageDialog(null, "Mobile_No is Mandatory!");   
        else if(email_fld.getText().equals(""))
             JOptionPane.showMessageDialog(null, "Email_Address is Mandatory!");
        else
           {  
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            try (Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/minp_login","root","Secreteng@4307")) {
                String sql="insert into profile_in values (?,?,?,?,?)";
                java.sql.PreparedStatement pst=con.prepareStatement(sql);
                pst.setString(1, namefld.getText());
                pst.setString(2, mobfld.getText());
                pst.setString(3,add_fld.getText());
                pst.setString(4, email_fld.getText());
                pst.setString(5, pass_fld.getText());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Updated Successfully");
                dispose();
                Login lg=new Login();
                lg.show();
            }
                  
            
            }catch(HeadlessException | ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        }
      
    }//GEN-LAST:event_create_btnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    dispose();
    Login disp= new Login();
    disp.show();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add_fld;
    private javax.swing.JButton create_btn;
    private javax.swing.JTextField email_fld;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mobfld;
    private javax.swing.JTextField namefld;
    private javax.swing.JPasswordField pass_fld;
    private javax.swing.JButton rst_btn;
    // End of variables declaration//GEN-END:variables
}
